version: "3.8"
services:
  db:
    image: postgres:15
    container_name: customer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customerdb
    ports:
      - "5432:5432"
